---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

---------------------------------

## Motivation 

Our project aims to address the critical public health challenge of HIV by understanding its distribution among racial groups in New York City. December 1, designated as World AIDS Day by the WHO, underscores the urgency of raising awareness and preventing the spread of HIV (HIV can progress to AIDS if left untreated). By identifying the most affected communities, we seek to uncover systemic issues like socioeconomic inequality and healthcare access disparities, guiding targeted interventions to reduce health inequities and promote social equity.

---------------------------------

## Related work 

Our inspiration stems from an article by the Associated Press titled “A twice-yearly shot could help end AIDS. But will it get to everyone who needs it?” This article highlights the groundbreaking potential of a twice-yearly injection for HIV prevention while shedding light on the persistent challenges of equitable access and affordability. Recognizing that systemic disparities in healthcare access, particularly among marginalized groups and regions like Latin America, hinder the global fight against HIV/AIDS, we were motivated to delve deeper into the trends and disparities in HIV/AIDS diagnoses. Our research aims to uncover the current status of progress in HIV/AIDS prevention, contributing to a better understanding of where interventions are most needed to promote global health equity in United States.

Link "https://apnews.com/article/hiv-infections-aids-prevention-shot-02606f7d7892f0baf55bd0a0ff2ba3de"

---------------------------------

## Initial questions 

The purposes of this project is to answer the following questions: 

*EDA?

1. Temporal Trends: How have HIV and AIDS diagnoses changed over time, and do specific neighborhoods experience disproportionately high rates?

2. Demographic Disparities: Are there significant disparities in HIV/AIDS diagnoses across sex and race/ethnicity?

3. Concurrent Diagnoses: Do concurrent HIV/AIDS diagnoses (late diagnoses) differ significantly across neighborhoods, and are these patterns influenced by other factors like race/ethnicity?
---------------------------------

## Data 

Source, scraping method, cleaning, etc.

---------------------------------

## Exploratory analysis 

Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.

---------------------------------

## Data Analysis

1. Temporal Trends



2. Demographic Disparities


3. Concurrent Diagnoses


---------------------------------

## Discussion

What were your findings? Are they what you expect? What insights into the data can you make?
